### ISSUE TITLE
System hangs in process.c

### ISSUE THREAD

**Issue by perlun** [chaos4ever/chaos#10]
For some reason, with the current code base, the system hangs in `process.c` when launching the first server. If I enable debugging in that same file, it does **not** hang (but instead it works, which means I could close #9), so this is really weird. I will use the good ole "printf" style debugging for this now...

**Comment by perlun** [comment]
I think I may be on to something now... [qemu](http://www.qemu.org) + some [debugging tricks from OSDev.org](http://wiki.osdev.org/Kernel_Debugging) helped me on the right track here. By enabling remote debugging in qemu, attaching `gdb` and then connecting to the qemu process, I managed to nail it down to this:

```
vagrant@packer-debian-7:/vagrant$ gdb
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) target remote localhost:1234
Remote debugging using localhost:1234
0x0010a80d in ?? ()
(gdb) symbol-file /vagrant/storm/ia32/storm
Reading symbols from /vagrant/storm/ia32/storm...done.
(gdb) bt
#0  0x0010a80d in mutex_spin_lock (spinlock=<optimized out>)
    at ../include/storm/current-arch/mutex.h:19
#1  mutex_kernel_wait (mutex=0x114164) at mutex.c:96
#2  0x00107168 in process_create (process_data=process_data@entry=0x3f3c) at process.c:182
#3  0x00102ada in elf_execute (image=image@entry=0x80000000 "\177ELF\001\001\001",
    parameter_string=0x4000 "/servers/vga", process_id=process_id@entry=0x103084) at elf.c:174
#4  0x00100445 in main (arguments=1, argument=0x116f44) at main.c:223
```

I looked now at the disassembled version of `mutex_spin_lock` and indeed, it doesn't seem entirely sound. If the mutex is already locked when the method enters, it will run into an infinite loop, which would very clearly explain this (weird) behavior. Will see if I can find a reasonable fix.
